// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace c_sharp_kafka.Schemas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class coord : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"coord\",\"namespace\":\"c_sharp_kafka.Schemas\",\"fields\":[{\"n" +
				"ame\":\"lon\",\"type\":\"float\"},{\"name\":\"lat\",\"type\":\"float\"}]}");
		private float _lon;
		private float _lat;
		public virtual Schema Schema
		{
			get
			{
				return coord._SCHEMA;
			}
		}
		public float lon
		{
			get
			{
				return this._lon;
			}
			set
			{
				this._lon = value;
			}
		}
		public float lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				this._lat = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.lon;
			case 1: return this.lat;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.lon = (System.Single)fieldValue; break;
			case 1: this.lat = (System.Single)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
