// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace c_sharp_kafka.Schemas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class main : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""main"",""namespace"":""c_sharp_kafka.Schemas"",""fields"":[{""name"":""temp"",""type"":""float""},{""name"":""feels_like"",""type"":""float""},{""name"":""temp_min"",""type"":""float""},{""name"":""temp_max"",""type"":""float""},{""name"":""pressure"",""type"":""int""},{""name"":""humidity"",""type"":""int""},{""name"":""sea_level"",""type"":""int""},{""name"":""grnd_level"",""type"":""int""}]}");
		private float _temp;
		private float _feels_like;
		private float _temp_min;
		private float _temp_max;
		private int _pressure;
		private int _humidity;
		private int _sea_level;
		private int _grnd_level;
		public virtual Schema Schema
		{
			get
			{
				return main._SCHEMA;
			}
		}
		public float temp
		{
			get
			{
				return this._temp;
			}
			set
			{
				this._temp = value;
			}
		}
		public float feels_like
		{
			get
			{
				return this._feels_like;
			}
			set
			{
				this._feels_like = value;
			}
		}
		public float temp_min
		{
			get
			{
				return this._temp_min;
			}
			set
			{
				this._temp_min = value;
			}
		}
		public float temp_max
		{
			get
			{
				return this._temp_max;
			}
			set
			{
				this._temp_max = value;
			}
		}
		public int pressure
		{
			get
			{
				return this._pressure;
			}
			set
			{
				this._pressure = value;
			}
		}
		public int humidity
		{
			get
			{
				return this._humidity;
			}
			set
			{
				this._humidity = value;
			}
		}
		public int sea_level
		{
			get
			{
				return this._sea_level;
			}
			set
			{
				this._sea_level = value;
			}
		}
		public int grnd_level
		{
			get
			{
				return this._grnd_level;
			}
			set
			{
				this._grnd_level = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.temp;
			case 1: return this.feels_like;
			case 2: return this.temp_min;
			case 3: return this.temp_max;
			case 4: return this.pressure;
			case 5: return this.humidity;
			case 6: return this.sea_level;
			case 7: return this.grnd_level;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.temp = (System.Single)fieldValue; break;
			case 1: this.feels_like = (System.Single)fieldValue; break;
			case 2: this.temp_min = (System.Single)fieldValue; break;
			case 3: this.temp_max = (System.Single)fieldValue; break;
			case 4: this.pressure = (System.Int32)fieldValue; break;
			case 5: this.humidity = (System.Int32)fieldValue; break;
			case 6: this.sea_level = (System.Int32)fieldValue; break;
			case 7: this.grnd_level = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
